name: Build every package in different environments.

on:
  push:
    branches:
      - 'master'
      - 'develop'
      - 'release/**'
  workflow_dispatch:

env:
  NODE_VERSION: 16

jobs:
  build-all:
    name: Build all packages in ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    steps:
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # https://github.com/actions/checkout/releases/tag/v2.3.4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@25316bbc1f10ac9d8798711f44914b1cf3c4e954 # https://github.com/actions/setup-node/releases/tag/v2.4.0
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
      - name: Install the dependencies
        run: npm ci
      - name: Build all packages
        run: npm run all build
