name: Docs Staging Deployment

env:
  GHA_DOCKER_TAG: docker.pkg.github.com/${{ github.repository }}/handsontable-documentation:9.0
  GHA_DOCKER_TAG_SHA: docker.pkg.github.com/${{ github.repository }}/handsontable-documentation:${{ github.sha }}

on:
  push:
    paths:
      - 'docs/**'
  workflow_dispatch:

defaults:
  run:
    working-directory: ./docs/

jobs:
  docker:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # v2

      - name: Docker login into GHCR
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login -u ${GITHUB_ACTOR} --password-stdin https://docker.pkg.github.com

      - name: Dependencies
        run: |
          npm ci

      - name: Generate API references
        run: |
          npm run docs:api

      - name: Docker build
        run: |
          npm run docs:docker:build

      - name: Docker tags
        run: |
          docker tag docs-md $GHA_DOCKER_TAG
          docker tag docs-md $GHA_DOCKER_TAG_SHA

      - name: Docker push latest into GHCR and deploy to the staging (only when manually dispatched)
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          docker push ${GHA_DOCKER_TAG}

      - name: Docker push SHA tagged into GHCR
        run: |
          docker push ${GHA_DOCKER_TAG_SHA}

      - name: Find PR
        uses: jwalton/gh-find-current-pr@b6f8d7342efe4913388d5d1ac7f4b956caa5db52 # https://github.com/jwalton/gh-find-current-pr/tree/v1
        id: pr-finder
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish sticky comment in PR
        uses: marocchino/sticky-pull-request-comment@6804b5ad49d19c10c9ae7cf5057352f7ff333f31 # https://github.com/marocchino/sticky-pull-request-comment/tree/v1.6.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          number: ${{ steps.pr-finder.outputs.pr }}
          message: |
            Launch the local version of documentation by running:
            ```bash
            npm run docs:review ${{ github.sha }}
            ```
